### PR TITLE
Mr meetups

### PR DESCRIPTION
**Pull request by spuuun**
hey gang. time for manageable AND mergeable conflicts!

### CODE REVIEW

**Comment by slochowsky** [comment]
god god good

**Comment by Ellie-Ash** [comment]
printToDom has already been declared

**Comment by noahbartfield** [comment]
printToDom error message

**Comment by noahbartfield** [comment]
Everything looks great. 50 results for "leather" 👍

**Comment by Ellie-Ash** [comment]
Matthew,
This code looks great. I have no problems with you pushing STRAIGHT to master.
Regards, 
Ellie

**Comment by slochowsky** [comment]
eh

**Pull request merged**
