### PR TITLE
Bs restaurants

### PR DESCRIPTION
**Pull request by slochowsky**
test everything, it probably don`t work

### CODE REVIEW

**Comment by Ellie-Ash** [comment]
it do work

**Comment by spuuun** [comment]
listen to noah

**Comment by noahbartfield** [comment]
On data.js. We don't need lines 15-18. We can make it modular later

**Comment by Ellie-Ash** [comment]
luuks guud

**Comment by noahbartfield** [comment]
Pulled Branch. No Error Message. Looks GREAT!!!!!!!!!!!

**Comment by spuuun** [comment]
browsed branch. noice. merge time

**Comment by Ellie-Ash** [comment]
no errors

**Pull request merged**
